config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :items
  resources :brands
  resources :user_items

root 'sessions#new'

post '/signin', to: 'sessions#create'

delete '/signout', to: 'sessions#destroy'

delete '/items/:id', to: 'items#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  belongs_to :business, class_name: 'User', foreign_key: 'business_id'

  validates_presence_of :name, :prestige, :location, :business

  has_attached_file :brand_image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :brand_image, content_type: /\Aimage\/.*\z/

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand
  has_many :user_items
  has_many :users, through: :user_items

  has_attached_file :item_image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :item_image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :brand_name, :brand_prestige, :brand_location
  has_many :user_items
  has_many :items, through: :user_items
  has_many :brands, foreign_key: 'business_id'

  validates_presence_of :name, :password, :email

  has_secure_password

  def brand_name=(brand_name)
    @brand_name = brand_name
  end

  def brand_prestige=(brand_prestige)
    @brand_prestige = brand_prestige
  end

  def brand_location=(brand_location)
    @brand_location = brand_location
  end

  def status_level
    return "Total Freebie Pro" if total_market_value > 500
    return "Freebie Novice" if total_market_value > 250
    return "Newbie" if total_market_value > 0
  end

  def total_market_value
    total = 0
    self.items.each do |item|
      total += item.market_value
    end
    total
  end

end

app/models/user_freeby.rb
class UserFreebie < ApplicationRecord
  belongs_to :user
  belongs_to :freebie
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  #protect_from_forgery with: :null_session

  helper_method :current_user, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/' unless logged_in?
  end

  def logged_in?
    !!session[:user_id]
  end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def new
    @brand = Brand.new
  end

  def create
    #binding.pry
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brand_path(@brand)
    else
      render :new
    end
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def index
    @brands = Brand.all
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :prestige, :location, :business, :brand_image)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def new
    @item = Item.new
  end

  def create
    @user = User.find(session[:user_id])
    @brand = @user.brands.first
  #  binding.pry
    @item = Item.new(name: item_params[:name], market_value: item_params[:market_value], gimmick: item_params[:gimmick], item_image: item_params[:item_image], brand_id: @brand.id)
    if @item.save
      redirect_to brand_path(@brand)
    else
      render :new
    end
  end

  def show
  end

  def index
    @items = Item.all
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to brand_path(@brand)
  end

  def destroy
    #binding.pry
    @user = User.find(session[:user_id])
    @brand = @user.brands.first
    Item.find(params[:id]).destroy


      redirect_to brand_path(@brand)

  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :market_value, :gimmick, :item_image, :id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #binding.pry
    #  if session[:user_id]
    #    #binding.pry
    #    @user = User.find(session[:user_id])
    #    if @user.brands.length > 0
    #      redirect_to brand_path(@user.brands.first)
    #    else redirect_to user_path(User.find(session[:user_id]))
    #    end
    #  end
  end

  def create
    #binding.pry
    user = User.find_by(email: session_params[:email])
      if user && user.authenticate(session_params[:password])
        session[:user_id] = user.id
        #binding.pry
        if user.brands.length > 0
          brand = user.brands.first
          redirect_to brand_path(brand)
        else redirect_to user_path(user)
        end
      else
        redirect_to '/', notice: 'Username or Password Not Correct'
      end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def session_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController

  def create
    #binding.pry
    user_item = UserItem.new(user_id: current_user.id, item_id: params[:item_id])
    if user_item.save
      redirect_to user_path(current_user.id)
    end
  end

  def destroy
    #binding.pry
    @user = User.find(session[:user_id])
    UserItem.find(params[:id]).destroy
      redirect_to user_path(@user)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :delete]

  def new
    @user = User.new
  end

  def create
    #binding.pry
    @user = User.new(name: user_params[:name], password: user_params[:password], email: user_params[:email])
    if @user.save
      #binding.pry
        if user_params[:brand_name] != nil && user_params[:brand_prestige] != nil && user_params[:brand_location] != nil
            #binding.pry
            @brand = Brand.create(name: user_params[:brand_name], prestige: user_params[:brand_prestige], location: user_params[:brand_location], business: @user)
            #binding.pry
        end
        session[:user_id] = @user.id
        if @user.brands.length > 0
          redirect_to brand_path(@user.brands.first)
        else redirect_to user_path(@user)
        end
    else
      render :new
    end
  end

  def show

  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def delete
  end


  def set_user
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :admin, :brand_name, :brand_prestige, :brand_location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/index.html.erb
<h2 align="center">Top 10 Freebies Collected </h2>
<p align="center">...or which freebies are most popular? </p>
<% items_sorted_by_count = Item.all.sort_by{|item| item.users.count}.reverse.take(10) %>

<% data = {
  labels: items_sorted_by_count.map{|item| "#{item.name}, #{item.brand.name}"},
  datasets: [
    {
        label: "Freebies Collected",
        backgroundColor: "rgba(220,220,220,0.2)",
        borderColor: "rgba(220,220,220,1)",
        data: Item.all.map{|item| item.users.count}.sort! { |x,y| y <=> x }
    }
  ]
} %>

<%= bar_chart data %>

app/views/brands/show.html.erb
<h1>Welcome Freebie Giver, <%= @brand.business.name %>. </h1> <br>

<div class="panel panel-default">
  <div class="panel-body">
<% if @brand.items.empty? %>
    You haven't logged any freebies yet :( <br>
    Log some freebies!
<% else %>
      <h2>Here's a list of freebies you currently offer!</h2>

          <table class="table table-striped">
            <tr>
              <th> Item name </th>
              <th> Item value </th>
              <th> Brand </th>
              <th> Picture </th>
              <th> </th>
            </tr>
          <% @brand.items.each do |item| %>
            <tr>
              <td>
                <a data-toggle="modal" data-target="#itemModal"> <%=item.name%></a>
                <!-- Modal -->
                <div class="modal fade" id="itemModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><%=item.name%></h4>
                      </div>
                      <div class="modal-body">
                        <p>Prestige Level: <%= item.brand.prestige * item.market_value %></p>
                        <p>Gimmick: <%= item.gimmick%></p>
                        <p>Number of people who have collected this item: <%=item.users.count %></p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div></td>
              <td> <%= "$#{item.market_value}" %> </td>
              <td> <%= item.brand.name %> </td>
              <td> <%= image_tag(item.item_image.url(:small)) %> </td>
              <td>
                <%= form_tag item_path(item.id), method: "delete" %>
                <%= submit_tag "X" %>
              </td>
            </tr>
              <% end %>
          </table>

<% end %>

</div>
</div>

<br>

  <a class="waves-effect waves-light btn modal-trigger" href="/items/new" data-target="#modal1" data-toggle='modal'>Add New Freebie</a>

  <div id="modal1" class="modal">
   <div class="modal-content">

   </div>
 </div>
 <br>
 <%= link_to 'View most popular freebies', brands_path %>

app/views/brands/view.html.erb
<h1>One Brand!</h1>

app/views/freebies/view.html.erb
<h1>One Freebie!</h1>

app/views/items/edit.html.erb
<h1>Edit your freebie!</h1>

<p><%if current_user.admin%>
  <%= form_for(@item) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :market_value %>
    <%= f.text_field :market_value %> <br>
    <%= f.collection_select :brand_id, Brand.all, :id, :name %><br>
    <%= f.file_field :image %> <br><br>

    <%= f.submit "Edit your freebie!"%>
  <% end %><br>
<p><%= link_to 'Delete this freebie :(', item_path(@item), :method => :delete%></p>
<%else%>

    <p>You must be a brand ambassador to edit a freebie!</p>

<%end%></p>

app/views/items/index.html.erb
<h1 class="text-center">All the Freebies!</h1>

  <% @items.each do |item| %>
  <div class="row">
    <div class="col s8 offset-s1">
      <h4 class="header"><%= item.name %></h4>

      <div class="card horizontal">
        <div class="card-image">
            <%= link_to image_tag(item.item_image.url(:large)), item.item_image.url %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <p><strong>Brought to You By: </strong><%= item.brand.name %></p>
            <p><strong>Prestige Level: </strong><%= item.brand.prestige * item.market_value %></p>
            <p><strong>Gimmick: </strong><%= item.gimmick%></p>
            <p><strong>Number of people who have collected this item: </strong><%=item.users.count %></p>
          </div>
          <div class="card-action <%=item.id%>">
            <%= form_tag user_items_path, method: :create do %>
            <% if current_user.items.include?(item) %>
              <%="You've already collected this freebie!"%>
            <% else %>
            <input type="hidden" name="item_id" value="<%=item.id%>" />
            <input type="submit" value="Add <%=item.name%> to my collection" />
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>
  <% end %>

app/views/items/new.html.erb
<h1>New Freebie!</h1>

  <%= form_for @item do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :market_value %>
    <%= f.text_field :market_value %> <br>
    <%= f.label :gimmick %>
    <%= f.text_field :gimmick %> <br>

    <%= f.file_field :image %> <br><br>
    <%= f.submit "Add your freebie!"%>
  <% end %>
  <br>
  <a href="#!" class="modal-action modal-close">Cancel</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreebieTrackerNetwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Freebie Tracker Network</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user && current_user.brands.length == 0 %>
        <li>
            <%= "Your status: #{current_user.status_level}" %>
        </li>
        <% end %>
        <% if current_user != nil%>
          <li>
            <%= link_to 'Log Out', signout_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit a User!<h1>

app/views/users/index.html.erb
<h1>All the Users!</h1>

<ul>
  <% @users.each do |user| %>
    <%= user.name %>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- Button trigger modal -->
<div class="col-md-12 text-center vert-align">
  <button type="button" id="new-user" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#userModal">
    I am a user.
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">User Sign Up</h4>
      </div>
      <div class="modal-body">
        <%= form_for @user, method: :post do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <br>
          <br>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <br>
          <br>
          <%= f.label :password %>
          <%= f.password_field :password %>
        <input type="submit" value="submit" class="btn btn-primary"></input>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Button trigger modal -->
<div class="col-md-12 text-center">
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#businessModal">
    I am a business.
  </button>
</div

<!-- Modal -->
<div class="modal fade" id="businessModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Business Sign Up</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@user) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <br>
          <br>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <br>
          <br>
          <%= f.label :password %>
          <%= f.password_field :password %>
          <br>
          <br>
          <%= f.label :brand_name %>
          <%= f.text_field :brand_name %>
          <br>
          <br>
          <%= f.label :brand_prestige %>
          <%= f.text_field :brand_prestige %>
          <br>
          <br>
          <%= f.label "Location" %>
          <%= f.text_field :brand_location %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome Freebie Getter, <%= @user.name %>. </h1> <br>

<div class="panel panel-default">
  <div class="panel-body">
<% if @user.items.empty? %>
<h4>You haven't collected any freebies yet :( <br>
Get on out there! Get some freebies! </h4>
<% else %>
<h3>Here's a list of the freebies you've collected:</h3>

<table class="table table-striped">
  <tr>
    <th> Item name </th>
    <th> Item value </th>
    <th> Brand </th>
    <th> Picture </th>
    <th> </th>
  </tr>
<% @user.user_items.each do |user_item| %>
  <tr>
    <td>
      <a data-toggle="modal" class= "user-freebie" data-target="#itemModal"> <%=user_item.item.name%></a>
      <!-- Modal -->
      <div class="modal fade" id="itemModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel"><%=user_item.item.name%></h4>
            </div>
            <div class="modal-body">
              <p>Prestige Level: <%= user_item.item.brand.prestige * user_item.item.market_value %></p>
              <p>Gimmick: <%= user_item.item.gimmick%></p>
              <p>Number of people who have collected this item: <%=user_item.item.users.count %></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div></td>
    <td> <%= "$#{user_item.item.market_value}" %> </td>
    <td> <%= user_item.item.brand.name %> </td>
    <td> <%= image_tag(user_item.item.item_image.url(:small)) %> </td>
    <td>
      <%= form_tag user_item_path(user_item.id), method: :delete do %>
      <input type="submit" value="Delete <%=user_item.item.brand.name%>" />
      <% end %>
    </td>
  </tr>
    <% end %>
</table>

<br>

<% end %>
</div>
</div>

<br><br>
      <%= link_to "Get More Freebies!", items_path %>

<br>

<p></p>